version: '3.1'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /foo/api.yml
    volumes:
      - ./:/foo
    ports:
      - "8080:8080"
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"